version: '3.3'
services:
  express:
    # image: node:16-alpine
    ports:
      - 8080:8080
    # volumes:
      # - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - UPLOAD_LIMIT=10M
    # working_dir: /app
    # command: pm2-runtime index.js